default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  database: <%= ENV.fetch("POSTGRES_DB") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV.fetch('POSTGRES_DB')}_test" %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
